services:
  database:
    image: postgres:17.5
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB="postgres"
    volumes:
      - pg_data:/var/lib/postgres/data

volumes:
  pg_data: